
insert into CLIENTS(CLIENT_ID) values(1)

insert into STOCKS(STOCK_ID,STOCK_SYMBOL,STOCK_AMOUNT,CLIENT_ID) values(1,'AAPL',2,1)
insert into STOCKS(STOCK_ID,STOCK_SYMBOL,STOCK_AMOUNT,CLIENT_ID) values(2,'FB',1,1)
insert into STOCKS(STOCK_ID,STOCK_SYMBOL,STOCK_AMOUNT,CLIENT_ID) values(3,'GOOGL',3,1)