CREATE TABLE IF NOT EXISTS CLIENTS (
	CLIENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS STOCKS (
	STOCK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	STOCK_SYMBOL VARCHAR(5) NOT NULL,
	STOCK_AMOUNT INT,
	CLIENT_ID BIGINT
);


ALTER TABLE STOCKS ADD FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID);
